### PR TITLE
rspec tests for custom enumerable methods

### PR DESCRIPTION
**Pull request by RokoVarano**
We have created tests for every case that each of the enumerable methods can take. In each of them, the custom Enumerable is compared to the output of the equivalent in-built Ruby Enumerable method

### CODE REVIEW

**Review by javitocor — CHANGES_REQUESTED** [review]
# STATUS CHANGES REQUIRED 🛑 

Hello team! 👋 
Good job setting up Rspec! 👍 
But we  need to implement some changes to approve the project 💪 
Kindly check my comments below 👇  apply the changes and resubmit your project for a new code review ⏩ 
Good luck! 😺 
## Mandatory changes
- Kindly add instructions in your readme file to install and run tests
- Improve the usage section in general, explain how to run the program, how to clone it...
- Improve the description of each test 'return the same as the original' it is not descriptive, what are you testing? i.e. 'calls the given block once for each element in self', and so on
- Test all the possible cases, what happens when no block is given? I.e. test all the possible cases the TSE's make you pass when building the enumerables

**Review by teekaytech — CHANGES_REQUESTED** [review]
## Status: Changes Required :warning: :vertical_traffic_light: 

### Hello team :wave:

__Good job so far :clap: 
You've made almost all the changes required by the previous reviewer.
We just have to make the other changes. 
Please check my comments below and fix them as appropriate.__

**[ REQUIRED CHANGES ]**
**_Your Readme is a form of documentation for your project. Therefore, always include all the necessary information so as to provide your users with all they needed to successfully use your project._**
- [x] As mentioned by the last reviewer, you should ensure to add instructions (on how to install and run the tests) to your Readme.MD file.
- [x] Also, be more expressive with the way you structure the `Usage` section of your Readme. Dumping the commands without telling your visitors where to type the command is not enough. Do not have the belief that all your users are programmers. Structure the usage section in such a way that any visitor will be able to read and understand how to set up your project. 


* * *
**Please make the required changes and submit another review request when you are done.**

* * *

**Taofeek Olalere
[Twitter](https://twitter.com/ola_lere) | [Github](https://github.com/teekaytech) | @taofeekolalere on Slack**
__Happy Coding :smiley:__

**Review by enaburekhan — CHANGES_REQUESTED** [review]
# Changes required:leo:
Hello team!
Good job :clap: on making the changes requested by the previous Tse. However, there's is still one more change you have to make to get this project approved  :muscle:.
**Mandatory requirements:**

- **Specs has to cover both positive and negative case scenarios. Currently, all your specs are checking only positive test cases.  You can start a  negative test case say like this: it "does not create the object if required attributes are missing..."**

Kindly make the above change and request for another review.

You can reach me on slack @enburekhan, if you have any questions.

Happy coding:blush:
Eric Enaburekhan

**Comment by RokoVarano** [comment]
@enaburekhan you are not available in Slack under that nick, so I will ask here:

This methods are supposed to work like their inbuilt equivalents, therefore, the tests must be a comparison. Now, the inbuilt methods in most cases always return an object, including when there are no parameters. The exception being #my_inject and #inject, in which case there is a test which checks that the correct type of error is raised. 
So considering this, how can we make a test where the object is not created?
And how can we make a negative test out of a comparison?

**Review by cristianCeamatu — APPROVED** [review]
### 🥇 APPROVED 🥇 Congratulations on the hard work! Good job on checking also for errors like `LocalJumpError`. Good luck with the next projects!

If you ever need any help or notice that you are wasting too many hours on a bug don't hesitate to contact me on Slack.

Best regards,
Cristian Ceamatu
Slack: Cristian Viorel Ceamatu

**Pull request merged**
